<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-30OAFHF" failures="1" tests="2" name="test" time="31.967" errors="0" timestamp="28 Sep 2018 08:27:15 GMT">
  <testcase classname="script.TestDemo" name="testA" time="1.323">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at script.TestDemo.testA(TestDemo.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testA -->
  <testcase classname="script.TestDemo2" name="testA" time="0.003"/>
</testsuite> <!-- test -->
